### PR TITLE
refactor: Rename to correct namespace

### PR DESCRIPTION
**Pull request by Ushie**

### CODE REVIEW

**Comment by riivx** [comment]
was this tested before? because i feel like some commits can break things

**Comment by riivx** [comment]
what are those changes? i can't see them in your fork 😭

**Comment by Ushie** [comment]
> already present in main, which are unrelated to this PR

https://github.com/vendetta-mod/VendettaManager/compare/main...sunset-mod:SunsetManager:main

**Comment by riivx** [comment]
ok, it means we have to still work on it

**Comment by Ushie** [comment]
yes, this PR only puts the correct namespace

once voof sets up the tracker, everything else can be done then

**Pull request closed without merging**
